In [49]:
import numpy as np
import pandas as pd

In [50]:
df = pd.read_csv('bert_2week_ordered.csv')
print(len(df))
df.head

2024

<bound method NDFrame.head of       Unnamed: 0        Date  bert_scores          Open          High  \
0           2023  2012-08-07     0.500000   5295.399902   5350.100098
1           2022  2012-08-08     0.333333   5345.250000   5377.600098
2           2021  2012-08-09     0.000000   5348.299805   5368.200195
3           2020  2012-08-10    -0.428571   5308.200195   5330.100098
4           2019  2012-08-13    -0.142857   5316.350098   5352.450195
...          ...         ...          ...           ...           ...
2019           4  2021-04-09     0.142857  14882.650391  14918.450195
2020           3  2021-04-12    -0.083333  14644.650391  14652.500000
2021           2  2021-04-13     0.222222  14364.900391  14528.900391
2022           1  2021-04-15     0.250000  14522.400391  14597.549805
2023           0  2021-04-16     0.166667  14599.599609  14697.700195

               Low         Close     Adj Close    Volume  windowSize_2  \
0      5281.649902   5336.700195   5336.700195       0.0      0.416667
1      5331.049805   5338.000000   5338.000000       0.0      0.166667
2      5312.100098   5322.950195   5322.950195       0.0     -0.214286
3      5294.100098   5320.399902   5320.399902       0.0     -0.285714
4      5309.049805   5347.899902   5347.899902       0.0     -0.008929
...            ...           ...           ...       ...           ...
2019  14785.650391  14834.849609  14834.849609  504100.0      0.029762
2020  14248.700195  14310.799805  14310.799805  650200.0      0.069444
2021  14274.900391  14504.799805  14504.799805  605100.0      0.236111
2022  14353.200195  14581.450195  14581.450195  568000.0      0.208333
2023  14559.000000  14621.750000  14621.750000       0.0      0.166667

      windowSize_3    week_1    week_2
0         0.277778  0.075680  0.079561
1        -0.031746  0.056200  0.022418
2        -0.190476  0.062152  0.012894
3        -0.148810  0.033581  0.005751
4         0.041667  0.166234  0.042857
...            ...       ...       ...
2019      0.093915  0.142857  0.142857
2020      0.129630 -0.083333 -0.083333
2021      0.212963  0.222222  0.222222
2022      0.250000  0.250000  0.250000
2023      0.166660  0.166667  0.166667

[2024 rows x 13 columns]>

In [51]:
#original scores
scores_1 = []
#print(scores_1)
for i in df['bert_scores']:
    scores_1.append(i)
print(scores_1[0:5])
print(len(scores_1))

[0.5, 0.3333333333333333, 0.0, -0.42857142857142855, -0.14285714285714285]
2024

In [52]:
# 1 day past scores
#66-33 weighted scores
#0.66 - 0.33x
scores_2 = [0.166666666]
for i in range(1,len(scores_1)):
    scores_2.append((scores_1[i]*0.66+scores_1[i-1]*0.33)) # x+x/2+x/3 ... to fit only 2 values
print(scores_2[0:5])
print(len(scores_2))

[0.166666666, 0.385, 0.11, -0.28285714285714286, -0.2357142857142857]
2024

In [53]:
#adding 1 day past column
df['2day_weighted'] = scores_2
df.head

<bound method NDFrame.head of       Unnamed: 0        Date  bert_scores          Open          High  \
0           2023  2012-08-07     0.500000   5295.399902   5350.100098
1           2022  2012-08-08     0.333333   5345.250000   5377.600098
2           2021  2012-08-09     0.000000   5348.299805   5368.200195
3           2020  2012-08-10    -0.428571   5308.200195   5330.100098
4           2019  2012-08-13    -0.142857   5316.350098   5352.450195
...          ...         ...          ...           ...           ...
2019           4  2021-04-09     0.142857  14882.650391  14918.450195
2020           3  2021-04-12    -0.083333  14644.650391  14652.500000
2021           2  2021-04-13     0.222222  14364.900391  14528.900391
2022           1  2021-04-15     0.250000  14522.400391  14597.549805
2023           0  2021-04-16     0.166667  14599.599609  14697.700195

               Low         Close     Adj Close    Volume  windowSize_2  \
0      5281.649902   5336.700195   5336.700195       0.0      0.416667
1      5331.049805   5338.000000   5338.000000       0.0      0.166667
2      5312.100098   5322.950195   5322.950195       0.0     -0.214286
3      5294.100098   5320.399902   5320.399902       0.0     -0.285714
4      5309.049805   5347.899902   5347.899902       0.0     -0.008929
...            ...           ...           ...       ...           ...
2019  14785.650391  14834.849609  14834.849609  504100.0      0.029762
2020  14248.700195  14310.799805  14310.799805  650200.0      0.069444
2021  14274.900391  14504.799805  14504.799805  605100.0      0.236111
2022  14353.200195  14581.450195  14581.450195  568000.0      0.208333
2023  14559.000000  14621.750000  14621.750000       0.0      0.166667

      windowSize_3    week_1    week_2  2day_weighted
0         0.277778  0.075680  0.079561       0.166667
1        -0.031746  0.056200  0.022418       0.385000
2        -0.190476  0.062152  0.012894       0.110000
3        -0.148810  0.033581  0.005751      -0.282857
4         0.041667  0.166234  0.042857      -0.235714
...            ...       ...       ...            ...
2019      0.093915  0.142857  0.142857       0.188571
2020      0.129630 -0.083333 -0.083333      -0.007857
2021      0.212963  0.222222  0.222222       0.119167
2022      0.250000  0.250000  0.250000       0.238333
2023      0.166660  0.166667  0.166667       0.192500

[2024 rows x 14 columns]>

In [54]:
# 2 day past scores
scores_3 = [0.16666,0.25000]
# 0.45 - 0.1x
for i in range(2,len(scores_1)):
    scores_3.append((scores_1[i]*0.45+scores_1[i-1]*0.35+scores_1[i-2]*0.25)/1.05)
print(scores_3[0:5])
print(len(scores_3))

[0.16666, 0.25, 0.21666666666666667, -0.1261904761904762, -0.21428571428571427]
2024

In [55]:
#adding column of 2 days past scores
df['3day_weighted'] = scores_3
#df = df.drop(['Unnamed: 0'], axis = 1)
df.head(8)

,Unnamed: 0,Date,bert_scores,Open,High,Low,Close,Adj Close,Volume,windowSize_2,windowSize_3,week_1,week_2,2day_weighted,3day_weighted
0,2023,2012-08-07,0.500000,5295.399902,5350.100098,5281.649902,5336.700195,5336.700195,0.0,0.416667,0.277778,0.075680,0.079561,0.166667,0.166660
1,2022,2012-08-08,0.333333,5345.250000,5377.600098,5331.049805,5338.000000,5338.000000,0.0,0.166667,-0.031746,0.056200,0.022418,0.385000,0.250000
2,2021,2012-08-09,0.000000,5348.299805,5368.200195,5312.100098,5322.950195,5322.950195,0.0,-0.214286,-0.190476,0.062152,0.012894,0.110000,0.216667
3,2020,2012-08-10,-0.428571,5308.200195,5330.100098,5294.100098,5320.399902,5320.399902,0.0,-0.285714,-0.148810,0.033581,0.005751,-0.282857,-0.126190
4,2019,2012-08-13,-0.142857,5316.350098,5352.450195,5309.049805,5347.899902,5347.899902,0.0,-0.008929,0.041667,0.166234,0.042857,-0.235714,-0.214286
5,2018,2012-08-14,0.125000,5343.250000,5387.049805,5328.799805,5380.350098,5380.350098,0.0,0.133929,0.210498,0.173655,0.040074,0.035357,-0.079464
6,2017,2012-08-16,0.142857,5385.950195,5390.649902,5356.649902,5362.950195,5362.950195,0.0,0.253247,0.293831,0.103850,-0.001322,0.135536,0.079464
7,2016,2012-08-17,0.363636,5368.600098,5399.950195,5341.700195,5366.299805,5366.299805,0.0,0.369318,0.179545,0.083442,-0.004383,0.287143,0.238636

In [31]:
#df = df.drop(['2week_weighted'], axis = 1)
#df.to_csv('Bert_9year_2-3_windowsize_weighted.csv')

In [59]:
# Scores for 7 days
scores_week1 = scores_1[0:6] 
# 0.42 - 0.06x
weight = [0.42,0.36,0.3,0.24,0.18,0.12,0.06]
#weight = [0.25,0.2,0.15,0.15,0.1,0.1,0.5]
for i in range(6,len(scores_1)):
    avg = 0
    for j in range(7):
        avg+=scores_1[i-j]*weight[j]
    scores_week1.append(avg/sum(weight))
print(scores_week1[0:8])
print(len(scores_week1))
#Adding column
df['1week_weighted'] = scores_week1

[0.5, 0.3333333333333333, 0.0, -0.42857142857142855, -0.14285714285714285, 0.125, 0.25833333333333336, 0.24061147186147186]
2024

In [60]:
# Scores for 14 days
scores_week2 = scores_1[0:13] 
# 0.26 - 0.02x 
weight = [0.26,0.24,0.22,0.2,0.18,0.16,0.14,0.12,0.1,0.08,0.06,0.04,0.02,0.0]
#weight = [0.15,0.13,0.11,0.1,0.09,0.08,0.07,0.06,0.05,0.04,0.04,0.03,0.3,0.2]
for i in range(13,len(scores_1)):
    avg = 0
    for j in range(14):
        avg+=scores_1[i-j]*weight[j]
    scores_week2.append(avg/sum(weight))
print(scores_week1[0:15])
print(len(scores_week2))

[0.5, 0.3333333333333333, 0.0, -0.42857142857142855, -0.14285714285714285, 0.125, 0.25833333333333336, 0.24061147186147186, 0.14951298701298704, -0.11509740259740259, 0.15115259740259743, 0.21667207792207793, 0.08120129870129869, 0.18795454545454549, 0.07431818181818181]
2024

In [61]:
#Adding column
df['2week_Weighted'] = scores_week2

In [62]:
df.head(19)

,Unnamed: 0,Date,bert_scores,Open,High,Low,Close,Adj Close,Volume,windowSize_2,windowSize_3,week_1,week_2,2day_weighted,3day_weighted,1week_weighted,2week_Weighted
0,2023,2012-08-07,0.500000,5295.399902,5350.100098,5281.649902,5336.700195,5336.700195,0.0,0.416667,0.277778,0.075680,0.079561,0.166667,0.166660,0.500000,0.500000
1,2022,2012-08-08,0.333333,5345.250000,5377.600098,5331.049805,5338.000000,5338.000000,0.0,0.166667,-0.031746,0.056200,0.022418,0.385000,0.250000,0.333333,0.333333
2,2021,2012-08-09,0.000000,5348.299805,5368.200195,5312.100098,5322.950195,5322.950195,0.0,-0.214286,-0.190476,0.062152,0.012894,0.110000,0.216667,0.000000,0.000000
3,2020,2012-08-10,-0.428571,5308.200195,5330.100098,5294.100098,5320.399902,5320.399902,0.0,-0.285714,-0.148810,0.033581,0.005751,-0.282857,-0.126190,-0.428571,-0.428571
4,2019,2012-08-13,-0.142857,5316.350098,5352.450195,5309.049805,5347.899902,5347.899902,0.0,-0.008929,0.041667,0.166234,0.042857,-0.235714,-0.214286,-0.142857,-0.142857
5,2018,2012-08-14,0.125000,5343.250000,5387.049805,5328.799805,5380.350098,5380.350098,0.0,0.133929,0.210498,0.173655,0.040074,0.035357,-0.079464,0.125000,0.125000
6,2017,2012-08-16,0.142857,5385.950195,5390.649902,5356.649902,5362.950195,5362.950195,0.0,0.253247,0.293831,0.103850,-0.001322,0.135536,0.079464,0.258333,0.142857
7,2016,2012-08-17,0.363636,5368.600098,5399.950195,5341.700195,5366.299805,5366.299805,0.0,0.369318,0.179545,0.083442,-0.004383,0.287143,0.238636,0.240611,0.363636
8,2015,2012-08-21,0.375000,5368.700195,5425.149902,5368.700195,5421.000000,5421.000000,0.0,0.087500,0.225000,-0.011364,-0.001786,0.367500,0.324594,0.149513,0.375000
9,2014,2012-08-22,-0.200000,5395.750000,5433.350098,5394.799805,5412.850098,5412.850098,0.0,0.150000,0.069697,-0.036364,-0.014286,-0.008250,0.113977,-0.115097,-0.200000
10,2013,2012-08-23,0.500000,5426.149902,5448.600098,5393.850098,5415.350098,5415.350098,0.0,0.204545,0.015152,-0.022078,0.008929,0.264000,0.230000,0.151153,0.500000
11,2012,2012-08-24,-0.090909,5392.600098,5399.649902,5371.000000,5386.700195,5386.700195,0.0,-0.227273,-0.151515,-0.080519,-0.018849,0.105000,0.094091,0.216672,-0.090909
12,2011,2012-08-27,-0.363636,5387.850098,5399.149902,5346.649902,5350.250000,5350.250000,0.0,-0.181818,-0.221212,-0.093506,0.016216,-0.270000,-0.095455,0.081201,-0.363636
13,2010,2012-08-28,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,-0.150000,-0.033333,-0.106494,0.050126,-0.120000,-0.145455,0.187955,0.222771
14,2009,2012-08-29,-0.300000,5343.850098,5345.500000,5282.700195,5287.799805,5287.799805,0.0,-0.050000,-0.066667,-0.092208,0.078698,-0.198000,-0.207727,0.074318,0.062771
15,2008,2012-08-30,0.200000,5268.600098,5342.799805,5255.049805,5315.049805,5315.049805,0.0,0.050000,0.063636,0.007792,0.123936,0.033000,-0.015000,-0.123636,0.036104
16,2007,2012-08-31,-0.100000,5298.200195,5303.250000,5238.899902,5258.500000,5258.500000,0.0,-0.004545,-0.063636,0.007792,0.117587,0.000000,-0.035000,0.174545,0.016104
17,2006,2012-09-03,0.090909,5276.500000,5295.799805,5243.149902,5253.750000,5253.750000,0.0,-0.045455,-0.181818,0.039935,0.096158,0.027000,0.045909,-0.094091,0.120000
18,2005,2012-09-04,-0.181818,5249.149902,5278.350098,5233.200195,5274.000000,5274.000000,0.0,-0.318182,-0.178788,0.042821,0.109145,-0.090000,-0.070000,-0.224091,0.112208

In [63]:
df.to_csv('Bert_9year_1-2week_weighted.csv') # final dataset